# Generated by Django 3.2.12 on 2022-03-24 07:41

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ecs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance_id', models.CharField(max_length=30, verbose_name='实例 id')),
                ('instance_type', models.CharField(max_length=30, verbose_name='实例规格')),
                ('instance_type_family', models.CharField(max_length=20, verbose_name='实例规格组')),
                ('image_id', models.CharField(max_length=60, verbose_name='实例镜像')),
                ('resource_group_id', models.CharField(max_length=30, verbose_name='资源组')),
                ('region_id', models.CharField(max_length=20, verbose_name='地域 id')),
                ('zone_id', models.CharField(max_length=20, verbose_name='可用区 id')),
                ('instance_charge_type', models.CharField(max_length=20, verbose_name='实例计费方式')),
                ('internet_charge_type', models.CharField(max_length=20, verbose_name='公网带宽计费方式')),
                ('creation_time', models.CharField(max_length=128)),
                ('expired_time', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hostname', models.CharField(max_length=128)),
                ('cloud_info', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cmdb.ecs', verbose_name='云主机信息')),
            ],
        ),
    ]
