# Generated by Django 3.2.12 on 2022-03-24 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0002_auto_20220324_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='instance_id',
            field=models.CharField(max_length=30, null=True, verbose_name='云主机实例 id'),
        ),
        migrations.AlterField(
            model_name='host',
            name='hostname',
            field=models.CharField(max_length=30, verbose_name='主机名'),
        ),
    ]
