# Generated by Django 3.2.12 on 2022-03-24 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0003_auto_20220324_1545'),
    ]

    operations = [
        migrations.CreateModel(
            name='CloudHost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance_id', models.CharField(max_length=30, verbose_name='实例 id')),
                ('instance_type', models.CharField(max_length=30, verbose_name='实例规格')),
                ('instance_type_family', models.CharField(max_length=20, verbose_name='实例规格组')),
                ('image_id', models.CharField(max_length=60, verbose_name='实例镜像')),
                ('resource_group_id', models.CharField(max_length=30, verbose_name='资源组')),
                ('public_ipaddress', models.JSONField(null=True, verbose_name='公网 ip')),
                ('region_id', models.CharField(max_length=20, verbose_name='地域 id')),
                ('zone_id', models.CharField(max_length=20, verbose_name='可用区 id')),
                ('instance_charge_type', models.CharField(max_length=20, verbose_name='实例计费方式')),
                ('internet_charge_type', models.CharField(max_length=20, verbose_name='公网带宽计费方式')),
                ('creation_time', models.DateTimeField(verbose_name='创建时间')),
                ('expired_time', models.DateTimeField(verbose_name='过期时间')),
            ],
        ),
        migrations.AlterField(
            model_name='host',
            name='cloud_info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cmdb.cloudhost', verbose_name='云主机信息'),
        ),
        migrations.DeleteModel(
            name='Ecs',
        ),
    ]
