# Generated by Django 3.2.12 on 2022-03-24 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0005_auto_20220324_1554'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cloudhost',
            name='creation_time',
        ),
        migrations.RemoveField(
            model_name='cloudhost',
            name='expired_time',
        ),
        migrations.RemoveField(
            model_name='cloudhost',
            name='image_id',
        ),
        migrations.RemoveField(
            model_name='cloudhost',
            name='instance_charge_type',
        ),
        migrations.RemoveField(
            model_name='cloudhost',
            name='internet_charge_type',
        ),
        migrations.RemoveField(
            model_name='cloudhost',
            name='public_ipaddress',
        ),
        migrations.RemoveField(
            model_name='cloudhost',
            name='region_id',
        ),
        migrations.RemoveField(
            model_name='cloudhost',
            name='resource_group_id',
        ),
        migrations.RemoveField(
            model_name='cloudhost',
            name='zone_id',
        ),
    ]
