# Generated by Django 3.2.12 on 2022-03-25 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0006_auto_20220324_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloudhost',
            name='creation_time',
            field=models.DateTimeField(null=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='cloudhost',
            name='expired_time',
            field=models.DateTimeField(null=True, verbose_name='过期时间'),
        ),
        migrations.AddField(
            model_name='cloudhost',
            name='image_id',
            field=models.CharField(max_length=60, null=True, verbose_name='实例镜像'),
        ),
        migrations.AddField(
            model_name='cloudhost',
            name='instance_charge_type',
            field=models.CharField(max_length=20, null=True, verbose_name='实例计费方式'),
        ),
        migrations.AddField(
            model_name='cloudhost',
            name='internet_charge_type',
            field=models.CharField(max_length=20, null=True, verbose_name='公网带宽计费方式'),
        ),
        migrations.AddField(
            model_name='cloudhost',
            name='public_ipaddress',
            field=models.JSONField(null=True, verbose_name='公网 ip'),
        ),
        migrations.AddField(
            model_name='cloudhost',
            name='region_id',
            field=models.CharField(max_length=20, null=True, verbose_name='地域 id'),
        ),
        migrations.AddField(
            model_name='cloudhost',
            name='resource_group_id',
            field=models.CharField(max_length=30, null=True, verbose_name='资源组'),
        ),
        migrations.AddField(
            model_name='cloudhost',
            name='zone_id',
            field=models.CharField(max_length=20, null=True, verbose_name='可用区 id'),
        ),
    ]
