# Generated by Django 3.2.12 on 2022-03-25 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0007_auto_20220325_1103'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cloudhost',
            old_name='public_ipaddress',
            new_name='public_ip_address',
        ),
    ]
