# Generated by Django 3.2.12 on 2022-03-25 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0008_rename_public_ipaddress_cloudhost_public_ip_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cloudhost',
            name='public_ip_address',
        ),
    ]
