# Generated by Django 3.2.12 on 2022-03-25 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0009_remove_cloudhost_public_ip_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloudhost',
            name='public_ip_address',
            field=models.JSONField(null=True, verbose_name='公网 ip'),
        ),
    ]
