# Generated by Django 3.2.12 on 2022-03-25 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0010_cloudhost_public_ip_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloudhost',
            name='instance_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='实例名称'),
        ),
        migrations.AlterField(
            model_name='cloudhost',
            name='internet_charge_type',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='公网带宽计费方式'),
        ),
    ]
